<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <RollForward>Major</RollForward>
    <PublishReadyToRun>false</PublishReadyToRun>
    <TieredCompilation>false</TieredCompilation>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>Platformer2D</AssemblyName>
    <AssemblyTitle>Platformer2D</AssemblyTitle>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>../Core/Content/Icon.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <MonoGameContentReference Include="..\Core\Content\Platformer2D.mgcb">
      <Link>Content\Platformer2D.mgcb</Link>
    </MonoGameContentReference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Core\Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="MonoGame.Framework.WindowsDX" Version="3.8.5-preview.*" />
    <PackageReference Include="MonoGame.Content.Builder.Task" Version="3.8.5-preview.*" />
  </ItemGroup>
</Project>