<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFrameworks>net9.0;net9.0-android</TargetFrameworks>
	</PropertyGroup>
	<ItemGroup Condition="'$(TargetFramework)'=='net9.0-android'">
		<PackageReference Include="MonoGame.Framework.Android" />
	</ItemGroup>
	<ItemGroup Condition="'$(TargetFramework)'=='net9.0'">
		<PackageReference Include="MonoGame.Framework.DesktopGL" />
	</ItemGroup>
</Project>