<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFrameworks>net8.0;net8.0-android</TargetFrameworks>
	</PropertyGroup>
	<ItemGroup Condition="'$(TargetFramework)'=='net8.0-android'">
		<PackageReference Include="MonoGame.Framework.Android" />
	</ItemGroup>
	<ItemGroup Condition="'$(TargetFramework)'=='net8.0'">
		<PackageReference Include="MonoGame.Framework.DesktopGL" />
	</ItemGroup>
</Project>