<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net9.0-ios</TargetFramework>
        <OutputType>Exe</OutputType>
        <SupportedOSPlatformVersion>12.2</SupportedOSPlatformVersion>
        <CodesignKey>iPhone Developer</CodesignKey>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="MonoGame.Content.Builder.Task" />
        <PackageReference Include="MonoGame.Framework.iOS" />
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="Gum.MonoGame" />
    </ItemGroup>
    <ItemGroup>
      <ProjectReference Include="..\DungeonSlime.Common\DungeonSlime.Common.csproj" />
    </ItemGroup>
</Project>