<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net9.0-ios</TargetFramework>
        <SupportedOSPlatformVersion>12.2</SupportedOSPlatformVersion>
        <BundleIdentifier>com.ogs.touchexample</BundleIdentifier>
        <CFBundleIconName>AppIcon</CFBundleIconName>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="MonoGame.Framework.iOS" />
    </ItemGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
        <CodesignKey>iPhone Distribution</CodesignKey>
        <CodesignEntitlements>EntitlementsProduction.plist</CodesignEntitlements>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
        <CodesignKey>iPhone Developer</CodesignKey>
        <CodesignEntitlements>Entitlements.plist</CodesignEntitlements>
    </PropertyGroup>

    <Target Name="CompileAssets" BeforeTargets="_CompileAppManifest" Condition="$([MSBuild]::IsOSPlatform('OSX'))">
        <MakeDir Directories="$(OutputPath)Assets" />
        <Exec Command="xcrun actool --output-format human-readable-text --notices --warnings --platform iphoneos --minimum-deployment-target 12.2 --app-icon AppIcon --output-partial-info-plist partial-info.plist --compile $(OutputPath)Assets Assets.xcassets " />
    </Target>

    <ItemGroup Condition=" '$(Configuration)' == 'Release' AND $([MSBuild]::IsOSPlatform('OSX')) ">
        <BundleResource Include="$(OutputPath)Assets/Assets.car">
            <LogicalName>Assets.car</LogicalName>
        </BundleResource>
    </ItemGroup>

</Project>