<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MonoGame.Framework.Native" Version="3.8.5-preview.*">
      <PrivateAssets>All</PrivateAssets>
    </PackageReference>
  </ItemGroup>  
  <ItemGroup>
    <ProjectReference Include="..\ShipGame.Dependencies\BoxCollider\BoxCollider.csproj" />
    <ProjectReference Include="..\ShipGame.Dependencies\NormalMappingModelProcessor\NormalMappingModelProcessor.csproj" ReferenceOutputAssembly="false" />
  </ItemGroup>

  <Target Name="BuildNormalMappingModelProcessorRelease" BeforeTargets="PrepareForBuild">
    <MSBuild
      Projects="..\ShipGame.Dependencies\NormalMappingModelProcessor\NormalMappingModelProcessor.csproj"
      Targets="Build"
      Properties="Configuration=Release" />
  </Target>
</Project>