<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net9.0-android</TargetFramework>
        <SupportedOSPlatformVersion>23</SupportedOSPlatformVersion>
        <OutputType>Exe</OutputType>
        <ApplicationId>com.companyname.DungeonSlime.Android</ApplicationId>
        <ApplicationVersion>1</ApplicationVersion>
        <ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
    </PropertyGroup>
    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
      <AndroidKeyStore>False</AndroidKeyStore>
    </PropertyGroup>
    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
      <AndroidKeyStore>False</AndroidKeyStore>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="MonoGame.Content.Builder.Task" />
        <PackageReference Include="MonoGame.Framework.Android" />
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="Gum.MonoGame" />
    </ItemGroup>
    <ItemGroup>
      <ProjectReference Include="..\DungeonSlime.Common\DungeonSlime.Common.csproj" />
    </ItemGroup>
</Project>