<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFrameworks>net9.0;net9.0-ios</TargetFrameworks>
	</PropertyGroup>
	<ItemGroup Condition="'$(TargetFramework)'=='net9.0-ios'">
		<PackageReference Include="MonoGame.Framework.iOS" />
	</ItemGroup>
	<ItemGroup Condition="'$(TargetFramework)'=='net9.0'">
		<PackageReference Include="MonoGame.Framework.DesktopGL" />
	</ItemGroup>
</Project>