<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-android</TargetFramework>
    <SupportedOSPlatformVersion>23</SupportedOSPlatformVersion>
    <OutputType>Exe</OutputType>
    <ApplicationId>com.companyname.NeonShooter.Android</ApplicationId>
    <ApplicationVersion>1</ApplicationVersion>
    <ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
  </PropertyGroup>
  <ItemGroup>
    <AndroidResource Include="Resources\Drawable\Splash.png" />
    <AndroidResource Include="Resources\Values\Styles.xml" />
  </ItemGroup>
  <ItemGroup>
    <MonoGameContentReference Include="..\NeonShooter.Core\Content\NeonShooter.mgcb" Link="Content\NeonShooter.mgcb" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\NeonShooter.Core\NeonShooter.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="MonoGame.Content.Builder.Task" Version="3.8.5-preview.*" />
    <PackageReference Include="MonoGame.Framework.Android" Version="3.8.5-preview.*" />
  </ItemGroup>
</Project>