# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  workflow_dispatch:
  push:
    branches:
      - '3.8.*'
  pull_request:
    branches:
      - '3.8.*'
  schedule:
    - cron: "0 3 * * 1"   # Weekly (Mon) build to keep artifacts fresh

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v5
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 9.0.x

    - name: Install .NET workloads
      run: |
        dotnet workload install macos
        dotnet workload install ios
        dotnet workload install android

    - name: Install MonoPack
      run: dotnet tool install --global MonoPack

    # Windows builds for all projects
    - name: Build Windows Binary for Tutorial/BasicCameraExample
      run: dotnet build Tutorials/BasicCameraExample/BasicCameraExample.sln

    - name: Archive Tutorial/BasicCameraExample
      uses: actions/upload-artifact@v6
      with:
        name: Windows-BasicCameraExample
        path: Tutorials/BasicCameraExample/**
        include-hidden-files: true

    - name: Build Windows Binary for AutoPong
      run: dotnet build AutoPong/AutoPong.WindowsDX/AutoPong.WindowsDX.csproj

    - name: Archive AutoPong
      uses: actions/upload-artifact@v6
      with:
        name: Windows-AutoPong
        path: AutoPong/**
        include-hidden-files: true

    - name: Build Windows Binary for FuelCell
      run: dotnet build FuelCell/FuelCell.WindowsDX/FuelCell.WindowsDX.csproj

    - name: Archive FuelCell
      uses: actions/upload-artifact@v6
      with:
        name: Windows-FuelCell
        path: FuelCell/**
        include-hidden-files: true

    - name: Build Windows Binary for NeonShooter
      run: dotnet build NeonShooter/NeonShooter.WindowsDX/NeonShooter.WindowsDX.csproj

    - name: Archive NeonShooter
      uses: actions/upload-artifact@v6
      with:
        name: Windows-NeonShooter
        path: NeonShooter/**
        include-hidden-files: true

    - name: Build Windows Binary for Platformer2D
      run: dotnet build Platformer2D/Platformer2D.WindowsDX/Platformer2D.WindowsDX.csproj

    - name: Archive Platformer2D
      uses: actions/upload-artifact@v6
      with:
        name: Windows-Platformer2D
        path: Platformer2D/**
        include-hidden-files: true

    - name: Build ShipGame Content Processor in Release mode
      run: dotnet build ShipGame/ShipGame.Dependencies/NormalMappingModelProcessor/NormalMappingModelProcessor.csproj --configuration Release

    - name: Build Windows Binary for ShipGame
      run: dotnet build ShipGame/ShipGame.WindowsDX/ShipGame.WindowsDX.csproj

    - name: Archive ShipGame
      uses: actions/upload-artifact@v6
      with:
        name: Windows-ShipGame
        path: ShipGame/**
        include-hidden-files: true

    - name: Build learn-monogame-2d Binary
      run: dotnet build Tutorials/learn-monogame-2d/src/27-Conclusion/DungeonSlime/DungeonSlime.csproj --configuration Release

    - name: Archive learn-monogame-2d
      uses: actions/upload-artifact@v6
      with:
        name: Windows-Learn-monogame-2d
        path: Tutorials/learn-monogame-2d/src/27-Conclusion/**
        include-hidden-files: true

    # Desktop builds for all projects
    - name: Build Desktop Binary for AutoPong
      run: dotnet build AutoPong/AutoPong.DesktopGL/AutoPong.DesktopGL.csproj

    - name: Package AutoPong for Linux-x64
      run: monopack AutoPong/AutoPong.DesktopGL/AutoPong.DesktopGL.csproj --runtime linux-x64 --output artifacts/Linux-x64/AutoPong

    - name: Package AutoPong for macOS-Universal
      run: monopack AutoPong/AutoPong.DesktopGL/AutoPong.DesktopGL.csproj --runtime osx-x64 --runtime osx-arm64 --output artifacts/macOS/AutoPong

    - name: Archive AutoPong Linux
      uses: actions/upload-artifact@v6
      with:
        name: Linux-AutoPong
        path: artifacts/Linux-x64/AutoPong/**
        include-hidden-files: true

    - name: Archive AutoPong macOS
      uses: actions/upload-artifact@v6
      with:
        name: macOS-AutoPong
        path: artifacts/macOS/AutoPong/**
        include-hidden-files: true

    - name: Build Desktop Binary for FuelCell
      run: dotnet build FuelCell/FuelCell.DesktopGL/FuelCell.DesktopGL.csproj

    - name: Package FuelCell for Linux-x64
      run: monopack FuelCell/FuelCell.DesktopGL/FuelCell.DesktopGL.csproj --runtime linux-x64 --output artifacts/Linux-x64/FuelCell

    - name: Package FuelCell for macOS-Universal
      run: monopack FuelCell/FuelCell.DesktopGL/FuelCell.DesktopGL.csproj --runtime osx-x64 --runtime osx-arm64 --output artifacts/macOS/FuelCell

    - name: Archive FuelCell Linux
      uses: actions/upload-artifact@v6
      with:
        name: Linux-FuelCell
        path: artifacts/Linux-x64/FuelCell/**
        include-hidden-files: true

    - name: Archive FuelCell macOS
      uses: actions/upload-artifact@v6
      with:
        name: macOS-FuelCell
        path: artifacts/macOS/FuelCell/**
        include-hidden-files: true

    - name: Build Desktop Binary for NeonShooter
      run: dotnet build NeonShooter/NeonShooter.DesktopGL/NeonShooter.DesktopGL.csproj

    - name: Package NeonShooter for Linux-x64
      run: monopack NeonShooter/NeonShooter.DesktopGL/NeonShooter.DesktopGL.csproj --runtime linux-x64 --output artifacts/Linux-x64/NeonShooter

    - name: Package NeonShooter for macOS-Universal
      run: monopack NeonShooter/NeonShooter.DesktopGL/NeonShooter.DesktopGL.csproj --runtime osx-x64 --runtime osx-arm64 --output artifacts/macOS/NeonShooter

    - name: Archive NeonShooter Linux
      uses: actions/upload-artifact@v6
      with:
        name: Linux-NeonShooter
        path: artifacts/Linux-x64/NeonShooter/**
        include-hidden-files: true

    - name: Archive NeonShooter macOS
      uses: actions/upload-artifact@v6
      with:
        name: macOS-NeonShooter
        path: artifacts/macOS/NeonShooter/**
        include-hidden-files: true

    - name: Build Desktop Binary for Platformer2D
      run: dotnet build Platformer2D/Platformer2D.DesktopGL/Platformer2D.DesktopGL.csproj

    - name: Package Platformer2D for Linux-x64
      run: monopack Platformer2D/Platformer2D.DesktopGL/Platformer2D.DesktopGL.csproj --runtime linux-x64 --output artifacts/Linux-x64/Platformer2D

    - name: Package Platformer2D for macOS-Universal
      run: monopack Platformer2D/Platformer2D.DesktopGL/Platformer2D.DesktopGL.csproj --runtime osx-x64 --runtime osx-arm64 --output artifacts/macOS/Platformer2D

    - name: Archive Platformer2D Linux
      uses: actions/upload-artifact@v6
      with:
        name: Linux-Platformer2D
        path: artifacts/Linux-x64/Platformer2D/**
        include-hidden-files: true

    - name: Archive Platformer2D macOS
      uses: actions/upload-artifact@v6
      with:
        name: macOS-Platformer2D
        path: artifacts/macOS/Platformer2D/**
        include-hidden-files: true

    - name: Build ShipGame Content Processor in Release mode
      run: dotnet build ShipGame/ShipGame.Dependencies/NormalMappingModelProcessor/NormalMappingModelProcessor.csproj --configuration Release

    - name: Build Desktop Binary for ShipGame
      run: dotnet build ShipGame/ShipGame.DesktopGL/ShipGame.DesktopGL.csproj

    - name: Package ShipGame for Linux-x64
      run: monopack ShipGame/ShipGame.DesktopGL/ShipGame.DesktopGL.csproj --runtime linux-x64 --output artifacts/Linux-x64/ShipGame

    - name: Package ShipGame for macOS-Universal
      run: monopack ShipGame/ShipGame.DesktopGL/ShipGame.DesktopGL.csproj --runtime osx-x64 --runtime osx-arm64 --output artifacts/macOS/ShipGame

    - name: Archive ShipGame Linux
      uses: actions/upload-artifact@v6
      with:
        name: Linux-ShipGame
        path: artifacts/Linux-x64/ShipGame/**
        include-hidden-files: true

    - name: Archive ShipGame macOS
      uses: actions/upload-artifact@v6
      with:
        name: macOS-ShipGame
        path: artifacts/macOS/ShipGame/**
        include-hidden-files: true

    - name: Build learn-monogame-2d Binary
      run: dotnet build Tutorials/learn-monogame-2d/src/27-Conclusion/DungeonSlime/DungeonSlime.csproj --configuration Release

    - name: Package learn-monogame-2d for Linux-x64
      run: monopack Tutorials/learn-monogame-2d/src/27-Conclusion/DungeonSlime/DungeonSlime.csproj --runtime linux-x64 --output artifacts/Linux-x64/learn-monogame-2d

    - name: Package learn-monogame-2d for macOS-Universal
      run: monopack Tutorials/learn-monogame-2d/src/27-Conclusion/DungeonSlime/DungeonSlime.csproj --runtime osx-x64 --runtime osx-arm64 --output artifacts/macOS/learn-monogame-2d

    - name: Archive learn-monogame-2d Linux
      uses: actions/upload-artifact@v6
      with:
        name: Linux-learn-monogame-2d
        path: artifacts/Linux-x64/learn-monogame-2d/**
        include-hidden-files: true

    - name: Archive learn-monogame-2d macOS
      uses: actions/upload-artifact@v6
      with:
        name: macOS-learn-monogame-2d
        path: artifacts/macOS/learn-monogame-2d/**
        include-hidden-files: true

  deploy:
      name: Deploy
      needs: [ build-windows ]
      runs-on: ubuntu-latest
      if: ${{ github.event_name == 'push' }}
      permissions:
          packages: write
          contents: write
      steps:
          - name: Clone Repository
            uses: actions/checkout@v4
          - name: Expose GitHub Runtime
            uses: crazy-max/ghaction-github-runtime@v3
          - name: Make a Release
            if: github.ref_type == 'tag'
            uses: ncipollo/release-action@v1
            with:
              name: 'MonoGame ${{ github.ref_name }}'
              tag: ${{ github.ref_name }}
              allowUpdates: true
              removeArtifacts: true
              artifacts: "*.zip"
              token: ${{ secrets.GITHUB_TOKEN }}
