<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0-ios</TargetFramework>
    <SupportedOSPlatformVersion>12.2</SupportedOSPlatformVersion>
    <CodesignKey>iPhone Developer</CodesignKey>
    <AssemblyName>Platformer2D</AssemblyName>
    <AssemblyTitle>Platformer2D</AssemblyTitle>
  </PropertyGroup>
  <ItemGroup>
    <MonoGameContentReference Include="..\Core\Content\Platformer2D.mgcb">
      <Link>Content\Platformer2D.mgcb</Link>
    </MonoGameContentReference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Core\Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="MonoGame.Content.Builder.Task" Version="3.8.*" />
    <PackageReference Include="MonoGame.Framework.iOS" Version="3.8.*" />
  </ItemGroup>
</Project>
